x-api-common: &api-common
    image: rinha.api
    build:
      context: .
      dockerfile: Rinha.Api/Dockerfile
    networks:
      - backend
      - payment-processor
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    expose:
      - "8080"

services:
  rinha1:
    <<: *api-common
  rinha2:
    <<: *api-common
    
  nginx:  
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - rinha1
      - rinha2
    networks:
      - backend
      - payment-processor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true